version: '3'

services:

  bot:
    build: .
    restart: always
    volumes:
      - .env:/app/bot/.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - 9999:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
    depends_on:
      - bot
